import { Product, Category } from "./types";

export const categories: Category[] = [
  {
    name: "Dresses",
    displayName: "Dresses",
    thumbnailImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBSJaVdU-Yp97KUrtuZAJRDERnslbMVGlbp8zpr_G8zwHIPrt5ccB9J5a0gIBFUpCOwTCeCuFTNit5FJPVRPJLnCcFE2ZhQwQz_-fSdHYCsF2eXEwZJpzXx5f6dztor6bfY9zvvLtsMx5AlWbemtHuNxHdQSfgNmyrGWKF-97ZLTY7KBViyxUNOt3ODHGXHyq3ryned5e3k78e-4Zr_pvYUtxDsyDJAo2Wv-wz4eHdXPTf-6gAIoQaWYeU25PSPhyojMZYSJnsnW50"
  },
  {
    name: "Outerwear",
    displayName: "Outerwear",
    thumbnailImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBUBUxvThoefWN2gPYiWDSUVwokFjbnw1OaSO7-JFyrj6PBdMLX4vtex30RsetAJ33Hgug6GTXrZ1QuH6GFva7AX4xHjEQGBs71gZ5oMJcnEILxd46fbk51iNVkrUSLkgR6vKkzeTi9dsKSXi3vRsc9439uMXjT4biUThN19HZHeNIPMQo9d_U6Kov5SgCLZPnkMYm-HHpYE79N8V61kWfgLjg1MJJSxSbzFIGx0Myg4yeeL-2V_m0FrjmK14z1K58j0Ey-i-GUAH0"
  },
  {
    name: "Accessories",
    displayName: "Accessories",
    thumbnailImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuCvypu-dUEgyEQDjmoIHiZHXWIcRknTm4T6sX3Y15QSnLf3O7S25C2so7BIf1azOZd49kD3O2mtRATxlX7uyNq7t0pKXoI1QsawCyl5FIYS76Xo6hQsq6_YwR1qevGsh9lSo_27obp4j5LnXJi0dPo72hmCKY0-q1iTecf_CXaNFIbvQ0gZb51lBjB6dswFbjiEDV2QcgM-Xy0uYz_70_VWSgjyk9gnx-XXoviiuaLG3z9Gd6Vz85Jt51zb3zWkRIgx6T0z-ZKqSiw"
  },
  {
    name: "Footwear",
    displayName: "Footwear",
    thumbnailImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuA8gTjOiUwNyQHIsxe0D3ih0eaNX5uRlhH8ftYAN-pDLswu9pH7KgOpg8BvEJEM5TSCOqmQlnvIODJozzgFa8kk1kJHxRLkrztjT909YM7nsptBs5-Cp5c9TAtuGGXo_NSgTOShfV0c3F03foAU2gio_Ecnznt4t2-nQwQODl3_tyhu8IShAlwNnrUgMFGT3KAbbkaN7Uyf6X3-Bf_QE6qocuJEZb-Rm8BuMLI2lAU-TqL5ssjSiwdmUFTO-RUODKK-a5cMrhlRnbk"
  },
  {
    name: "Tailoring",
    displayName: "Tailoring",
    thumbnailImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuAHTvRRfbvpwtA4ReXlzPxxvFjHmYaf9zvuGIfr2p-bx4tH6teC6bITpsjpxh7zUnnjtHqEvJPD_5KB9Qob1nKyr-q7bXkE2MhtbeEiNx4XYvFvV4sueAN3DADhdgx6p20v8FuWZ32kq5YnS5F5ZWQlnASbIo91dQ4lojECnHiPTV6Q44SoE6E9-qcjEMZkbuhjpemMuxRPPj69B9h2MiouMV5vqJDvMQ5naTeqVYfnhFWBTTrpZ0iS7fnGmNZRg2pNETShvEZe8FA"
  }
];

export const products: Product[] = [
  {
    id: "fluid-silk-slip-dress",
    title: "Fluid Silk Slip Dress",
    subtitle: "Collection № 04",
    price: 890,
    description: "A masterclass in minimalist draping. This bias-cut silhouette is crafted from 32mm heavy-weight mulberry silk, designed to trace the contours of the body with a liquid-like finish. Featuring delicate adjustable straps and a raw-edge hem.",
    material: "100% Mulberry Silk",
    origin: "Milan, Italy",
    sizes: ["XS", "S", "M", "L"],
    categories: ["Dresses"],
    mainImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPeOLVpYX8AArLWueEhfJVXNpbQaz7kstoCrEOxqvSOtHitciOf7rh0XTkmGBfng81LbBwyNI8nN6Uwjeigmj54y6GXi7lVrideJOLvJooqBZC8YT6oOzO5KfxGa0IlW3mL_sKfrR-lvZwvaiDEJDWDVNxvm-i3u4sTWnARr31MgbskTWV580j6jkuSF4sfoVgHt2w7pyK3gBg5mOwinrDZYriuNtOI3J3N-1_Gnk2qZ3v07OWrSdrGFvceJeL6SPVjAIau24uRzw",
    galleryImages: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBPeOLVpYX8AArLWueEhfJVXNpbQaz7kstoCrEOxqvSOtHitciOf7rh0XTkmGBfng81LbBwyNI8nN6Uwjeigmj54y6GXi7lVrideJOLvJooqBZC8YT6oOzO5KfxGa0IlW3mL_sKfrR-lvZwvaiDEJDWDVNxvm-i3u4sTWnARr31MgbskTWV580j6jkuSF4sfoVgHt2w7pyK3gBg5mOwinrDZYriuNtOI3J3N-1_Gnk2qZ3v07OWrSdrGFvceJeL6SPVjAIau24uRzw",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBpkKP_ZyaC5JOQMv4yCwUSrEzhHCgMG37K30xI8JFAPwYTZD2xxmiLgWlWWrF-NnTx5U9a7eHZz3iGmYO5oO5HnaPUusIXeMD9YaJIfRfvbvzOPzpkiPaoLCYmdsQMpu_oCd_hATlq-NJRg-8PI6-Zhn2eHWo0tXc-hC8Zp4odTW9BEY8RbcH8Rb_VCM0XGctYPk2TLprbi3sa6AWOOCaVa2kXe92kAjtuMyB02Qmgh54vj-Z3D5a6i-a_Fdx4_VCryQ4qeTwqPfM",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDxYlaab3avIwOron6RYsQWyEAQGr6S6m1kFgCw1S2P0PMrPybqeHOa-EnB2WfuZ8AWVax5-XUxx8eVrwMCF9jxlOtuJAm-Bm31FpnR_oXSvxTTfydUKPhAJy6oWql9z2rU1lm3OD-m1ZxTB5g6k3o6tp6A9tagt_Fg4cm-C9iOplDZjyS9KjK8nuUmKIYnyij84f3eua00d1twlHUsUPqOvpibFIIGpkLMDylWIYf8hBjbrRE-2BYxUnbMTTc6AY3rcT-t5XCVkWk",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDSepdBKduIBWbgmYmBidKet9Ucwyaq0LGkg1x9n-By8WHSM0-aPhg1rwFj_1Y7_NRAFPg1iqnHLUDsQrBO-Z95LPLDNy_foa7M88HL9SGgY3v3DjOe8yKlvMpy8CkMPYXHqnn-rZ3XcZNJ9gsOvCQd4nKrgCnv6fN04w7tqdEATVl5aHKo8mGExaK-9BJFdb5lBF1L9CyJOoQlLmhMV3PF2u-xI9uw8tz7y7g65KFeULrIN9I5PatJNZOXm2toQQzfO60I6wA0Wy8"
    ],
    sustainability: "Our silk is OEKO-TEX® certified, ensuring no harmful chemicals are used in the production process. We partner with family-owned mills in Lake Como to ensure ethical labor and eco-friendly dye processes.",
    careInstructions: "Dry clean only. Store on a padded hanger to maintain the bias-cut structure. Do not steam at high temperatures.",
    color: "MONO",
    fabric: "SILK"
  },
  {
    id: "the-archival-trench",
    title: "The Archival Trench",
    subtitle: "100% Virgin Wool",
    price: 1240,
    description: "An archival classic highlighting structured shoulders and beautiful asymmetric lines. Engineered for seamless layered silhouettes with fluid warmth.",
    material: "100% Virgin Wool",
    origin: "Florence, Italy",
    sizes: ["XS", "S", "M", "L"],
    categories: ["Outerwear", "Tailoring"],
    mainImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuApYsvpdRsRuz-CYxlD8bddEP4LDufTAE72JrWLoyMcwX9qz0pmIGHJKxjb4zOio8USQ_HAfaU8tBrxAqI1rdXVhLN1Ac6zZSoyyjTx_ScDvX1IuiGKpKEPewHuDPPi63JxY4U1RgoUEDloXbH9iv6IpdmFUoKruL1--M6NUud8DydhJ15Y8SOwDAaV0BFZZT_tQFxMJIVfil-2ege9S1BUC2pamtu06b7PhYYP4gOTVTIk_f_hQFkRJTxWHNOjNWTnMl6f9Usc8Gk",
    sustainability: "100% biodegradable pure wool sourced from certified sustainable farms in Tuscany, processed using closed-loop water treatment facilities.",
    careInstructions: "Professional dry clean only. Brush with a soft fabric brush to maintain wool luster.",
    color: "MONO",
    fabric: "WOOL"
  },
  {
    id: "structure-top",
    title: "Structure Top",
    subtitle: "Sculpted Canvas",
    price: 480,
    description: "Sculpted heavyweight canvas top focusing on custom geometry. Features clean raw-edge lines and a tailored waist ideal for layering or high-waisted separates.",
    material: "Heavy Cotton Canvas Blend",
    origin: "Milan, Italy",
    sizes: ["S", "M", "L"],
    categories: ["Tailoring"],
    mainImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuA0Oa5NwuxNmtGKYk7WaR0jE8K3b9rTqYrn1yO9TjTsCHOjLPPLuhtmeAx83GWzo-4tQdxQMexMSuwX4TakbQkoWBZSbmyaazwZ0_E7T3cLvpx1U_90Z137oSKwsRiDM_inKTKkh8OJNqypa9XDVzcQopGQ5NBiBGMS_FVheA9Td6k-7uYYFCVHQZdVcSUX5nvlbZk2mO8Z7i7THNzjbZKf1g-7dNl9i6DsGtFE7X0oUiE8HxQvecuCuk4emIU7Cwg0jvfNzaecQ3w",
    sustainability: "Crafted from organically grown industrial cotton, utilizing zero-waste pattern drafting techniques.",
    careInstructions: "Hand wash cold with delicate detergent or dry clean to maintain structured waistline lines.",
    color: "MONO",
    fabric: "COTTON"
  },
  {
    id: "silk-narrative",
    title: "Silk Narrative",
    subtitle: "Mulberry Silk",
    price: 390,
    description: "A delicate wrap camisole silhouette designed with mulberry silk. Offers a fluid fit with elegant adjustable thin back-straps and clean flatlock details.",
    material: "100% Mulberry Silk",
    origin: "Lake Como, Italy",
    sizes: ["XS", "S", "M"],
    categories: ["Dresses", "Accessories"],
    mainImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBDkbqTiGSEkIJBW6ECqef_6Z3OuFgVCC0k7y4Tfvu-hz5mSaCOENt8k_nxOV_AZuRkNk91e2dR-kdci75hV87nQNijLAZk_w4qbJmGZmjwDEi_3n2GmP38uqiGLpHR3ZXnA9daZdTTYBWa2dhOoJHpkEeQ7o9QKzrn0R58T3mSWaHZsZj3zbc8RUv-1Fr0lhL_Cvp6NZtVzWrd6ABZcDJCXrcDycc8pczCrsCMecwBX2ACtv3xSM0s5c-9jO7kCr5i8mtHiYyk5kI",
    sustainability: "Sourced from local organic silk weavers in Italy. Dyed with GOTS certified non-toxic organic colors.",
    careInstructions: "Gentle hand wash cold or delicate dry clean. Iron inside out at lowest setting.",
    color: "MONO",
    fabric: "SILK"
  },
  {
    id: "the-void-trousers",
    title: "The Void Trousers",
    subtitle: "Relaxed Fit Cotton",
    price: 550,
    description: "Minimalist wide-leg trousers exploring negative space. Detailed with deep front pleating and structured side slip pockets for high comfort.",
    material: "90% Organic Cotton, 10% Fine Linen",
    origin: "Bologna, Italy",
    sizes: ["XS", "S", "M", "L"],
    categories: ["Tailoring"],
    mainImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuAXlheGTbu06nZmepHQ61V6IxJzgPpd-NXwoRDLeVijIIwZerqhTn5Z5V6VamlDanAWUVap1gkaIouPcglUpzfs5K72ePweUdvNclbQavmb8ui5nJbSp1NKclVawfcDFO0OXqfFREr5p7vLj73hCfgQ-d1K9rCov5Kdw6qAwFREaA0c4sSHvm8OiXbcNFU_IM8b04n4DKfcVuUCY8fPkge10g1jm4Qc1zvx9FK0yDtR8OMIY4I_vMpTRPSzvMfBIQGuyZ61nJ_pnxc",
    sustainability: "Crafted in a carbon-neutral factory in Bologna from ethically certified organic cotton fibers.",
    careInstructions: "Machine wash cold inside out with similar colors. Hang dry naturally. Warm iron.",
    color: "MONO",
    fabric: "COTTON"
  },
  {
    id: "leather-obscura",
    title: "Leather Obscura",
    subtitle: "Calfskin Accessories",
    price: 210,
    description: "Monochromatic luxury calfskin low sneakers. Minimalist panel construction with ultra-soft hand-finished leather lining and durable natural rubber soles.",
    material: "100% Premium Calfskin Leather",
    origin: "Naples, Italy",
    sizes: ["S", "M", "L"],
    categories: ["Footwear", "Accessories"],
    mainImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBrVpztCumLNBoAItFeOmuvk3f7I9J7dI2Cux0WS_1EFfYkjVp0UtaExlIar94q8V-FGB6tOgevReYSv3Tw-fWRO30TuLHGiWE3_enU1Wjm5JHhVwN9i9Oj89-NkWYO3mQlYedFWSGhb-IiP7mIOZBk-LwPP7dGN0KKM26wZ5x2wf0bkOONtcbrvcCXfeeBOClKdyr-uJUsd11xSzJiLjW6rLeaU0I1BgtItEI75tP-UCkkHBb5IQaLmhkdDi7Sk34iHShzuhCJ3mU",
    sustainability: "Leather tanned in LWG Gold-certified Italian tanneries utilizing eco-efficient chrome-free processing.",
    careInstructions: "Wipe clean with a damp soft cloth. Store in customized cotton dust bag using shoetrees.",
    color: "MONO",
    fabric: "LEATHER"
  },
  {
    id: "linear-layering",
    title: "Linear Layering",
    subtitle: "Seasonal Set",
    price: 890,
    description: "An editorial collection exploring asymmetrical volume ratios. Stacks naturally with fine knits or tailored outer pieces to evoke a sculptural look.",
    material: "80% Virgin Wool, 20% Cashmere",
    origin: "Turin, Italy",
    sizes: ["XS", "S", "M", "L"],
    categories: ["Tailoring"],
    mainImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuAnqpDt0A4LrUz4DUFet98zPoD70Dy2Rukt5Pw8piXcwEdcie42Vc3gTZvUeO2Ud9GPLeP47DBwvRYjjnsJ2HqrUVBMud2hr038w_TpNfKkN4nrqf6_gQ39gxnBglwAEO_yjeZfIp6UsWm3rcSTwMtuC4jWfivJyQ-hSHWaLmjFTxQl0vAXDyAms-NVeyRhs_IvpKHy2fS3HLxoj2nh_5jFoVMiO62Crw6C-iXTRGGn7Z-CUsMfIVMYPFznHXK0hoESmYFPS9kEaTA",
    sustainability: "Sourced from animal welfare certified sheep farms in Piedmont. Manufactured with zero chemical waste output.",
    careInstructions: "Steam clean or dry clean only. Flat dry in shade. Avoid tumble drying at all costs.",
    color: "MONO",
    fabric: "WOOL"
  },
  {
    id: "sculpted-silk-gown",
    title: "Sculpted Silk Gown",
    subtitle: "Autumn / Winter '24",
    price: 2450,
    description: "A striking, elegant floor-length silk gown featuring deep architectural plunging neck lines and structured drape lines that flow gracefully with every movement.",
    material: "100% Organza Silk",
    origin: "Rome, Italy",
    sizes: ["S", "M"],
    categories: ["Dresses"],
    mainImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuAXjm9gytZ_vcWUwuQtTUMW7UVTAGFj0tPbYXZa_Pb5veWnmekt9H4g_dD1BYk-gKY6P4W-55ImCXo7tVwRNaKQpvRHRVUljk5-ka7xFJ2ESLobdWw0V5tjiat3TloS6UFTRnSSKcqHWnxPfOMt2Vsw3RuLE_afbkAKafGbRUYzU-FlcmWLyW2lf8DFRMjJNXRNqlsZbOj5xklFzvlvKzByQVpQQ_rqhafTiVGiXXLMgdSLRih2uS28gVQmd5l1tiXULhOb5B8fd7Y",
    sustainability: "Made in limited quantities in Rome to prevent surplus inventory. Dyed with ecological herbal extracts.",
    careInstructions: "Professional delicate dry clean only. Handle with care. Avoid snagging against sharp items.",
    color: "MONO",
    fabric: "SILK"
  },
  {
    id: "archive-clutch",
    title: "Archive Clutch",
    subtitle: "Hand-crafted Leather",
    price: 890,
    description: "A highly-structured modern classic. Crafted with robust boxcalf leather, raw edge linings, and custom solid brass elements for timeless visual poise.",
    material: "100% Boxcalf Leather & Suede Lining",
    origin: "Florence, Italy",
    sizes: ["ALL"],
    categories: ["Accessories"],
    mainImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuCfCXnEoxSjm1vprDCZIO6xHGH4yyRMrAWoA0tdrYH1frMCHvrGY4V-ZZhXqiSM9kCn3qSQUvmnHioppH0PYXbG3rbYfkPaHKcsn3ZR8ql8d0e1YRexykhOPPIDOFMizI-KMK1spqGVVokHHgaEDlkdYqWOqoLb96JprRCRYp01BQC4GcvojMubvOv8ciX0N9Vo7njV3GrCND80HH79hmAixUYDGere_37Ohx0hXD0yf5GGXhDnx5AZSPTVgVvJfIiFRoudsiRMvAA",
    sustainability: "Hand-crafted entirely in a multi-generational leather atelier using deadstock leather remnants.",
    careInstructions: "Condition regularly with mild leather cream. Keep away from water and direct heat.",
    color: "MONO",
    fabric: "LEATHER"
  },
  {
    id: "structured-blazer",
    title: "Structured Blazer",
    subtitle: "Wool Blend",
    price: 1200,
    description: "Elegant double-breasted structured blazer cut in premium Virgin Wool. Highlights clean oversized lapels and raw-lined inner seams for comfortable structure.",
    material: "85% Virgin Wool, 15% Italian Silk",
    origin: "Milan, Italy",
    sizes: ["XS", "S", "M", "L"],
    categories: ["Tailoring"],
    mainImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDa0AOJS1_hnUDp5sTjQBKwvZnErVdmSuRWibtbC2OxMO3YBdF2vh_CiiLc9g_tCKxgdGq3f10v4ukY2SsANfrB5kW-0aMpcnjq9nK-RtqAa7SX3BP5m-wuXR_TYoE1NXh5PDBD029VzWutYrCp9U6_6jKmmgoey9jm9pV_FkDAw5oL8lu3Ab2Msrhy1Cg_bidj5l8QCmmqjnpTydARkfmVWXqsW2mpfBjTQ5FpodtSNI1PCE9YUPZcu-7Bc6WJUCCx5wJcEsP4MhE",
    sustainability: "Wool sourced ethically in northern Italy. Manufactured with 100% renewable power in Milan.",
    careInstructions: "Professional dry clean only. Place on broad wooden hangers to protect the shoulder canvas structure.",
    color: "MONO",
    fabric: "WOOL"
  },
  {
    id: "lumiere-trench",
    title: "Lumière Trench",
    subtitle: "Limited Edition",
    price: 3100,
    description: "An avant-garde interpretation of the classic trench coat. Boasts extra-long storm flaps, custom raw-finish hems, and an ultra-cinched tailored belt structure.",
    material: "75% Gabardine Cotton, 25% Cultivated Silk",
    origin: "Tokyo, Japan",
    sizes: ["S", "M", "L"],
    categories: ["Outerwear"],
    mainImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuCY3wii-Z4qR0xFlKFPvv4vnkF_KTx2WERbN3fhmhdFxcIPOg2Xqx3nhnMLnNOaeuiT1JTmbY3IfHPS17KWSGxk5SPK6oVgMACf8_1yJHFqSqfGig6p218DlZ_NqVliWOvJcvyLTTmrKMcAjchrkZ5zShL-fujANRW9C-4arGKku9eklL5rhtuGkMtYkALlqKAKdF1Ye3Vn7mzV3VNl25R28XBPMPsvJgKpSwlxQKMbjUUttFxJIxX7Ue-cvdjJH-j72QnK0s8QSnA",
    sustainability: "Made in partnership with small sustainable heritage farms in Tokyo. No plastic elements or synthetic threads.",
    careInstructions: "Professional dry clean only. Iron carefully with defensive protective cotton layer.",
    color: "MONO",
    fabric: "COTTON"
  },
  {
    id: "strappy-heel",
    title: "Strappy Heel",
    subtitle: "Calfskin Block Heel",
    price: 420,
    description: "Stunning minimalist strappy sandal boasting an architectural profile. Structured with block stacked wood heels and full calfskin support strap systems.",
    material: "100% Calfskin Upper, Solid Oak Heel",
    origin: "Venice, Italy",
    sizes: ["XS", "S", "M", "L"],
    categories: ["Footwear"],
    mainImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDUa8Fu2pirc21alV0kkll4JTC40cGCnw0R0lD7k_-HsA2nh2k13E2KyefEiT0Zd_ziUQV9MUizb_5FHh3DB9FNZknNjgBZOaWqzwlbjZqy171-6RR5WPBfoizFR5ieFmMM3fQqEVYQbn5jfNegF4s-OV3aPsgAcPoCyO691SyCdLb4ePWzBOlOR_5VSCq9dfZkI8NK4H4Go-61c2Jcj-H3y3R7A1h858ASGCDQzK8K-R_CLWq2WBVgb0AFiUGZG2pgX_sVFlISjLw",
    sustainability: "Utilizes timber sourced from responsibly managed forests (FSC certified) and vegetable-tanned lining leathers.",
    careInstructions: "Store in a dry location. Wipe calfskin straps with specialized leather cleaner. Use protective heel covers.",
    color: "MONO",
    fabric: "LEATHER"
  },
  {
    id: "vault-clutch",
    title: "Vault Clutch",
    subtitle: "Calfskin Leather",
    price: 1250,
    description: "Sleek and highly structured luxury clutch, featuring geometric lines, a blind gold-embossed logo, and brushed-brass custom slide closures.",
    material: "100% Smooth Calfskin Leather",
    origin: "Florence, Italy",
    sizes: ["ALL"],
    categories: ["Accessories"],
    mainImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuCrWKCDpYrQY5Y7xe2byqE9mqOxrNaH1XtNMSzh_Xi0XARmUiKjkHskAPUjweDZa0UM7yAOouBh1kekBYosEf55vumCopVrk352BLZGvz9eZzsrCLgMwb7zwYEyqq6U5Dec6A5ld5RY27r55Tu_R94pH1YWe4XTNMy6zYvlqlImuh_X0qZ3t_wajzH1UIGWgyjIcAegb73Q8p3uPvlu9IoOwMNj_8vt7QTM0dTbiRI9demAzK2WLy9hK-1tv_mNJK3wxzAIdcFHGp0",
    sustainability: "100% hand-crafted in a certified ethical small workspace using responsibly sourced local leather.",
    careInstructions: "Avoid direct contact with cosmetic products or water. Polish brass hardware with a microfiber clean cloth.",
    color: "MONO",
    fabric: "LEATHER"
  },
  {
    id: "helix-earrings",
    title: "Helix Earrings",
    subtitle: "18k Solid Gold",
    price: 310,
    description: "Bold sculptural hoop earrings inspired by helical biology. Hand-finished with organic asymmetric curves and premium butterfly closures.",
    material: "18k Recycled Solid Gold",
    origin: "Arezzo, Italy",
    sizes: ["ALL"],
    categories: ["Accessories"],
    mainImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuCrELrCmyNDCC7YEA2Sm9L-Yfore6rKn2vzEnwixIwR8vLXAsInPPl-HaFyZ0FNr2TgqNKdCXT81ok7BXrzjwNE94XVApkZbpWQqjw1AriPkQmFOE_MQ8fYloAHOXsnSGky4IUSnOkFh6tNOmrorkjmsk9296TXAnCh5JY8OZIt2aWfarsaa45VtGj6krcgin_45Jvf39c33Spx7R8lUoh4ZlmRHVg5PRQxxTETeCWa8y697slhXAvS_GodmW-8o-9Tsl-thZ_uWZw",
    sustainability: "Crafted entirely from 100% recycled gold certified by the Responsible Jewellery Council (RJC).",
    careInstructions: "Clean gold carefully with specialized gentle jewelry wash. Store in protective velvet-lined container.",
    color: "GOLD",
    fabric: "METAL"
  }
];
